### ISSUE TITLE
failed to download album with forward slash in name

### ISSUE THREAD

**Issue by daedalus1337** [daedalus1337/red#10]
Acoustic Alchemy - American/English

the forward slash caused it to fail to download.  I'm sure there's an encoding thing that can be done to the search input to fix this.

**Comment by shersch** [comment]
hm... I wonder if I fixed this.  will have to check one day

**Comment by daedalus1337** [comment]
i wonder if i fixed this

**Comment by daedalus1337** [comment]
turns out I stopped troubleshooting this because I already tried to download it 4 times and the API won't let me anymore :P.  Guess I'll have to wait for another album to pop up that has a slash in it.
